apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
  - port: 8080
    name: http
  - port: 35729
    name: live
  type: LoadBalancer
  selector:
    app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: proxy
        image: gcr.io/dga-demo/proxy
      - name: ui
        image: gcr.io/dga-demo/ui
        ports:
        - containerPort: 8080
        - containerPort: 35729

