apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaniko-cache-pv
spec:
  capacity:
    storage: 10G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /kaniko
    server: 10.237.231.98
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-cache-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10G